# Generated by Django 4.0.4 on 2022-04-30 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conference', '0003_conference_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenceBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250)),
                ('department', models.CharField(max_length=250)),
                ('date_field', models.DateField()),
                ('time_from', models.TimeField()),
                ('time_to', models.TimeField()),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.conference')),
            ],
        ),
    ]
